# Pipeline for updating concourse environment.
groups:
- name: concourse
  jobs:
  - bbl-up
  - bosh-upload-stemcell
  - bosh-deploy-concourse
  - bosh-cleanup
  - bosh-delete-concourse
  - bbl-destroy

resources:
- name: bbl-state
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/infrastructure-ci-bbl-states.git
    private_key: {{github_private_key}}

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: concourse-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/concourse-deployment.git

jobs:
- name: bbl-up
  serial: true
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
    - get: bbl-config
      resource: bbl-state
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_STATE_DIR: concourse
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{service_account_key}}
      BBL_GCP_REGION: {{region}}
      BBL_LB_CERT: {{ssl_cert}}
      BBL_LB_KEY: {{ssl_cert_private_key}}
      LB_DOMAIN: {{concourse_domain}}
      BBL_ENV_NAME: concourse
  - put: bbl-state
    params:
      rebase: true
      repository: updated-bbl-state

- name: bosh-upload-stemcell
  plan:
  - aggregate:
    - get: concourse-deployment
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
      passed: [bbl-up]
      trigger: true
  - task: bosh-upload-stemcell-from-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-concourse-deployment/task.yml
    params:
      BBL_STATE_DIR: concourse

- name: bosh-deploy-concourse
  plan:
  - aggregate:
    - get: concourse-deployment
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
      passed: [bosh-upload-stemcell]
      trigger: true
    - get: ops-files
      resource: concourse-deployment
    - get: vars-files
      resource: bbl-state
    - get: vars-store
      resource: bbl-state
  - task: bosh-deploy-concourse
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: concourse
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{service_account_key}}
      SYSTEM_DOMAIN: {{concourse_domain}}
      OPS_FILES: "operations/use-compiled-releases.yml"
      USE_VARS_STORE: false
  - put: bbl-state
    params:
      rebase: true
      repository: updated-vars-store

- name: bosh-delete-concourse
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
      passed: [bosh-deploy-concourse]
  - task: bosh-delete-concourse
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: concourse

- name: bosh-cleanup
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
      resource: bbl-state
      passed: [bosh-delete-concourse]
  - task: bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: concourse

- name: bbl-destroy
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: bbl-state
      passed: [bosh-cleanup]
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: concourse
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{service_account_key}}
  - put: bbl-state
    params:
      rebase: true
      repository: updated-bbl-state
