---

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.7.0

inputs:
- name: bbl-state
- name: ci

run:
  path: ci/tasks/upload-stemcell

params:
  BBL_STATE_DIR: bbl-state
  BBL_GCP_SERVICE_ACCOUNT_KEY:
