#!/bin/bash
set -eux

function upload_stemcell() {
  set +e
  local existing_stemcell
  existing_stemcell=$(bosh stemcells | grep "trusty" | awk '{print $2}' | tr -d "\*")
  set -e

  if [ "${existing_stemcell}" ]; then
    echo "Stemcell already exists.  Exiting..."
    return
  fi

  bosh -n upload-stemcell "https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent"
  set -x
}

function main() {
  set +ux
  pushd bbl-state/"${BBL_STATE_DIR}"
    eval "$(bbl print-env)"
  popd
  set -ux
  upload_stemcell
}

main

